### ISSUE TITLE
Build from source does not work (PyPi)

### ISSUE THREAD

**Issue by cgr71ii** [mbanon/fastspell#7]
Hi!

I'm trying to install FastSpell from source from PyPi, but it does not work:

```bash
pip install fastspell --no-binary :all:
```

Output:
```
Collecting fastspell
  Downloading fastspell-0.1.5.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-q_4drfze/fastspell_c25a265c2e0d408385954a75dd70ca53/setup.py", line 10, in <module>
          with open("requirements.txt") as rf:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

The problem seems to be that the file `requirements.txt` has not been included in the package https://files.pythonhosted.org/packages/1f/e6/95b99433b85bb1260f5e2440dba985ad41bd41a356918f285ecc41deded3/fastspell-0.1.5.tar.gz

**Comment by mbanon** [comment]
Should be fixed with 8bbcedd1bc642011229d9c97902be9b94e5e756d 

It's also uploaded to PyPI:  https://pypi.org/project/fastspell/

Thanks!
